# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-logging'
set -g @plugin 'catppuccin/tmux'

# Refresh more often
set -g status-interval 2

# N00bs use mice
set -g mouse on

# Yes, we count from 0, but that button is so far away
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Rice our setup
set-option -g set-titles on 
set -g @catppuccin_status_modules_right "application session user host date_time"
set -g @catppuccin_window_default_text "#{b:window_name}"

# VI keys
setw -g mode-keys vi

# Copy mode
set -s set-clipboard external

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
