blacklist = ["scratch"]

[[session]]
name = "notes"
path = "~/Documents/Obsidian Vault/"
startup_command = "nvim +ObsidianToday"

[[session]]
name = "getbelch"
path = "~/src/github.com/fatzombi/getbelch/"

[[session]]
name = "dotfiles"
path = "~/src/github.com/fatzombi/dotfiles/"

[[session]]
name = "neovim config"
path = "~/src/github.com/fatzombi/dotfiles/nvim"

[[session]]
name = "tmux config"
path = "~/src/github.com/fatzombi/dotfiles/tmux"

[[session]]
name = "zsh config"
path = "~/src/github.com/fatzombi/dotfiles/zsh"

[[session]]
name = "ghostty config"
path = "~/src/github.com/fatzombi/dotfiles/ghostty"

[[session]]
name = "aerospace config"
path = "~/src/github.com/fatzombi/dotfiles/aerospace"
startup_command = "nvim aerospace.toml"
preview_command = "bat --style='full' --color=always ~/src/github.com/fatzombi/dotfiles/aerospace/aerospace.toml"

[[session]]
name = "redbeard"
path = "~/src/github.com/fatzombi/redbeard"

