# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'dracula/tmux'

# Refresh more often
set -g status-interval 2

# N00bs use mice
set -g mouse on

# Yes, we count from 0, but that button is so far away
set -g base-index 1

# Rice our setup
set -g @dracula-plugins "cpu-usage ram-usage"
set -g @dracula-show-powerline true

# VI keys
setw -g mode-keys vi

# Copy mode
set -s set-clipboard external

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
